application: feefie98052
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail
- channel_presence
- warmup

builtins:
- deferred: on
- admin_redirect: on

handlers:
- url: /_ah/channel/disconnected/
  script: garbage_collect.application

- url: /_ah/channel/connected/
  script: connected.application

- url: /_ah/mail/.+
  script: lib.email_dispatch.application

- url: /static
  static_dir: static

- url: /command
  script: lib.dispatch.application

- url: /js
  static_dir: lib/js

- url: /css
  static_dir: lib/css

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /_ah/warmup
  script: warmup.application
